clean: ;

install:
	install -d $(DESTDIR)/usr/lib/java/ilom-redirect
	install -d $(DESTDIR)/usr/bin
	install -m 644 JavaRConsole.jar $(DESTDIR)/usr/lib/java/ilom-redirect/JavaRConsole.jar
	install -m 644 RedirLib.jar $(DESTDIR)/usr/lib/java/ilom-redirect/RedirLib.jar
	install -m 644 linuxi386.jar $(DESTDIR)/usr/lib/java/ilom-redirect/linuxi386.jar
	install -m 755 ilom-redirect $(DESTDIR)/usr/bin/ilom-redirect
